### ISSUE TITLE
paper and code

### ISSUE THREAD

**Issue by flynnamy** [yiyulics/CSEC#1]
Hi, could you please share the paper and code? @yiyulics

**Comment by yiyulics** [comment]
Thank you for your interest in our work.

I've uploaded a version of the paper to Google Drive, which you can access via the following link: [csec.pdf - Google Drive](https://drive.google.com/file/d/1jZB2rW_I2WLTE5yNA4IZq9wb5p4NNOCR/view?usp=drive_link). Please be aware that IEEE holds the copyright for this document. I plan to update the link once the CVF has officially released the papers.

Currently, I am focused on preparing a submission for NeurIPS, which has occupied much of my time. I intend to clean up and release the associated code as soon as possible.

**Update: The Google Drive link is invalid now. Please refer to the arXiv or CVF version for the full paper. Thanks.**

**Comment by oscarlorente** [comment]
Hi! Any updates on this?

**Comment by CastoHu** [comment]
Hello, could you please release some inference code and weights first?

**Comment by xuhangc** [comment]
any updates

**Comment by vishxlyadav** [comment]
@yiyulics 
Congratulations on CVPR acceptance!!
Would you please release the code? it would be very helpful.

**Comment by n0kovo** [comment]
BUMP

**Comment by yiyulics** [comment]
Code has been released. Thank you for your interest. I'm closing this post as nothing more can be done.
