### ISSUE TITLE
再别的数据集上不行

### ISSUE THREAD

**Issue by ShuimuChen-hyq** [yiyulics/CSEC#10]
您好，将您的代码用在LOL数据集上最终得到的cpkt，在测试集上会出错，但用您预训练的模型就没问题，这是什么原因呢，难不成是我的python是3.9版本，但您给的environment文件里python是3.7
![微信截图_20241122171108](https://github.com/user-attachments/assets/49e09ef0-1dae-4d5a-9f79-6d2ad78c3bf1)

**Comment by yiyulics** [comment]
请问可以提供完整的报错信息吗？

**Comment by ShuimuChen-hyq** [comment]
![微信截图_20241123203846](https://github.com/user-attachments/assets/b0a59606-9097-4b8a-910a-b7f77772f7fe)
![微信截![微信截图_20241123203846](https://github.com/user-attachments/assets/b0a59606-9097-4b8a-910a-b7f77772f7fe)
![微信截图_20241123203859](https://github.com/user-attachments/assets/5de827b6-58b8-48cf-942b-f79e6e16e546)
您好，运行test文件会出现这种问题，cuda索引会超出，当然这是使用其他数据集LOL上的预训练ckpt,如果用您的数据集训练的预训练ckpt就没问题，解决办法只能用CPU进行测试，但时间会很长很长。还有个小问题，对于train过程，其SSIM和PSNR我不能直接看到吗，除了用tensorboard看到外，我现在是在LOL数据集上看到output很好（在tensorboard上看的），但一测试output就很差很差图_20241123203859](https://github.com/user-attachments/assets/5de827b6-58b8-48cf-942b-f79e6e16e546)
您好，运行test文件会出现这种问题，cuda索引会超出，当然这是使用其他数据集LOL上的预训练ckpt,如果用您的数据集训练的预训练ckpt就没问题，解决办法只能用CPU进行测试，但时间会很长很长。还有个小问题，对于train过程，其SSIM和PSNR我不能直接看到吗，除了用tensorboard看到外，我现在是在LOL数据集上看到output很好（在tensorboard上看的），但一测试output就很差很差

**Comment by ShuimuChen-hyq** [comment]
<img width="287" alt="f2a356d871102877617444fc06c0893" src="https://github.com/user-attachments/assets/fa96189c-07e0-4f34-9bdd-a0a676a023fa">
<img width="297" alt="dd540d4011e92757aaa0afe02f13c8a" src="https://github.com/user-attachments/assets/d0d29aba-03da-4f7f-a2c7-c53dbc0b3282">
<img width="495" alt="cd6e4aca10add68cb033ad198e622c2" src="https://github.com/user-attachments/assets/ebbe1b49-3675-41ad-a77b-ff73099c9066">
可以看到测试很烂，但训练的tensorboard上显示还可以

**Comment by ShuimuChen-hyq** [comment]
还请您解答我这个疑问，是不是训练和测试不大一样

**Comment by yiyulics** [comment]
1. 对于test遇到的问题，根据提供的两张截图，我没有办法定位问题的来源，如果可以的话，请用`> logs.txt`保存log信息并附件方便我们定位问题；
2. 对于train时的psnr和ssim问题，我猜测您指的是validation阶段的psnr和ssim？我不是很明白您的问题，您希望在哪里能看到？您可以修改对应的`validation_step`并提出PR；
3. 对于LOL数据集上的test结果的问题，请您详细说明获得test output的步骤以帮助我们复现结果，根据图片结果初步猜测是这张图是某一个阶段的intermediate feature map并不是final output。

**Comment by ShuimuChen-hyq** [comment]
![image](https://github.com/user-attachments/assets/7ce09d2d-6898-41ad-8655-98759649edc5)
![image](https://github.com/user-attachments/assets/b34736af-fca4-49a8-8a23-2d995b101e1a)
![image](https://github.com/user-attachments/assets/45dbab7f-b99b-4bab-bf96-8ee456e44cfc)
![image](https://github.com/user-attachments/assets/84d7cabb-4ef8-40aa-abb5-930acca0a613)
train过程由于您启用了tensorboard，具体在tb_logs中，可以看到step 112,000的输出结果还是很好的，我训练采用的是LOL数据集的485张图片，测试不论使用它给的15张验证集，还是我训练的485张图片，效果都不好，如你所见，严重色差偏色，但可以看到tensorboard上面给出的结果可以的，如果tensorboard不可信，您代码训练过程输出的图片如下，效果确实可以呀
![image](https://github.com/user-attachments/assets/f520e14b-fecb-4c62-afa5-bdacbb4e459c)

**Comment by 2402227288** [comment]
然后在训练过程中，我只能在tensorboard上面看到您论文给的loss，并不能看到psnr和ssim评估指标我想问出了用tensorboard看之外，没有其他办法看中间的lossloss指标了把，psnr和ssim得自己修改代码？

**Comment by ShuimuChen-hyq** [comment]
然后在训练过程中，我只能在tensorboard上面看到您论文给的loss，并不能看到psnr和ssim评估指标我想问出了用tensorboard看之外，没有其他办法看中间的lossloss指标了把，psnr和ssim得自己修改代码？
![image](https://github.com/user-attachments/assets/140e9461-3ab3-42d4-91eb-e5c2252154ac)

**Comment by ShuimuChen-hyq** [comment]
然后对于最近训练到1399epoch的模型测试出现了以下问题
![image](https://github.com/user-attachments/assets/1f31864b-ba44-404f-be51-5af9f633a841)
显示数组超出索引，是我图像大小的问题还是训练的cpkt文件问题呢

**Comment by yiyulics** [comment]
1. 建议以训练过程中输出的图片结果为准，我train的时候没有参考tensorboard的结果，只是沿用了原代码库里tensorboard的设置，因此不能确认tensorboard的结果是否准确，后续有时间会double-check一下；
2. 训练过程中validation的psnr和ssim可以在tensorboard上显示，修改很容易；
3. 对于training过程中的这个问题我并没有遇到过，我不能确定是什么引起的问题，还是建议您提供`> logs.txt`与完整的环境配置以便于我们复现您的问题。

**Comment by ShuimuChen-hyq** [comment]
好的那我没有问题了，感谢您了
