### ISSUE TITLE
MSEC测试集GT

### ISSUE THREAD

**Issue by wyn04** [yiyulics/CSEC#6]
你好，MSEC测试集有五个专家的结果作为GT，论文里只有一个结果，请问是取平均值还是取哪个专家的结果作为GT？

**Comment by yiyulics** [comment]
We use the retouched images in the MSEC dataset labeled "expert_c" as our ground truth, following the approach in the original MSEC paper. For further details, please refer to the "Our Dataset" section of the [MSEC paper](https://openaccess.thecvf.com/content/CVPR2021/papers/Afifi_Learning_Multi-Scale_Photo_Exposure_Correction_CVPR_2021_paper.pdf#page=3.5).

**Comment by yiyulics** [comment]
If you have no further questions, I will close this issue.
