### ISSUE TITLE
测试错误

### ISSUE THREAD

**Issue by ShuimuChen-hyq** [yiyulics/CSEC#9]
您好，按照要求进行预训练模型测试时，出现了版本不兼容的情况
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/home/shuimuchen/anaconda3/envs/3.91/lib/python3.9/site-packages/torchmetrics/utilities/imports.py)
我安装的torchmetrics为1.6.0，而torch为2.5.1

**Comment by yiyulics** [comment]
我这里的运行的版本是`pytorch_lightning==1.7.6`以及`pytorch==1.12.1`。过新的版本`pytorch_lightning`以及其对应的`pytorch`版本并不兼容。请按照README的安装要求进行安装。

**Comment by ShuimuChen-hyq** [comment]
那我用您发的yaml文件创建虚拟环境可以吗

**Comment by ShuimuChen-hyq** [comment]
您的yaml文件中显示pytorch=1.10.0=py3.7_cuda11.3_cudnn8.2.0_0，torch是1.10.0而cuda是11.3

**Comment by yiyulics** [comment]
可以的。yaml里的版本是另一个机器上我配的环境，yaml的版本和readme里的版本我测试过都没有问题。

**Comment by 2402227288** [comment]
GT和input inmage一定要对齐吗，不对齐好像会报错，一直卡住

**Comment by ShuimuChen-hyq** [comment]
在测试预训练模型时，GT和input images一定要对齐吗，下载的数据集好像每个GT会对应很多种不同风格的input images，需要自己手动处理使得和GT数目一样吗，而且后续还出现了终端不可用的情况

**Comment by yiyulics** [comment]
你是指MSEC数据集吗？可以参考这里的写法：https://github.com/onpix/LCDPNet/issues/23#issuecomment-1913260345

**Comment by ShuimuChen-hyq** [comment]
感谢所有问题都解决了
